### ISSUE TITLE
XL size images are looking pixelated

### ISSUE THREAD

**Issue by Ananthakr** [tusharjo/flagit#1]
Since, the flag icon set is an PNG file, the XL and LG sizes look a little pixelated. Can we explore SVG for clarity and reduced bundle size?
<img width="446" alt="Screenshot 2021-01-05 at 3 10 23 PM" src="https://user-images.githubusercontent.com/12773390/103630841-45badf80-4f68-11eb-8bb0-94b1fbac0c45.png">

**Comment by tusharjo** [comment]
is now fixed in the latest version.
